services:
  gophermart:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      RUN_ADDRESS: ":8080"
      DATABASE_URI: "postgres://gophermart:gophermart@host.docker.internal:5432/gophermart?sslmode=disable"
      ACCRUAL_SYSTEM_ADDRESS: "host.docker.internal:8081"
    restart: unless-stopped
